gestion des estudiantes/Gestion.web/Models/ErrorViewModel.cs
namespace Gestion.web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

gestion des estudiantes/Gestion.web/Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gestion.Infrastructure.Context;
using Gestion.domain.Entities;

namespace Gestion.web.Controllers
{
    public class EstudianteController : Controller
    {
        private readonly GestionContext _context;

        public EstudianteController(GestionContext context)
        {
            _context = context;
        }

        // GET: Estudiante
        public async Task<IActionResult> Index()
        {
            return View(await _context.Estudiantes.ToListAsync());
        }

        // GET: Estudiante/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiantes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estudiante == null)
            {
                return NotFound();
            }

            return View(estudiante);
        }

        // GET: Estudiante/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Estudiante/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Sexo,Edad,Matricula,NombrePadre,TelefonoPadre,NombreMadre,TelefonoMadre,Domicilio,Curso,Necesidades,Intervenciones,Resultados")] Estudiante estudiante)
        {
            if (ModelState.IsValid)
            {
                _context.Add(estudiante);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(estudiante);
        }

        // GET: Estudiante/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiantes.FindAsync(id);
            if (estudiante == null)
            {
                return NotFound();
            }
            return View(estudiante);
        }

        // POST: Estudiante/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Sexo,Edad,Matricula,NombrePadre,TelefonoPadre,NombreMadre,TelefonoMadre,Domicilio,Curso,Necesidades,Intervenciones,Resultados")] Estudiante estudiante)
        {
            if (id != estudiante.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estudiante);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstudianteExists(estudiante.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(estudiante);
        }

        // GET: Estudiante/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiantes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estudiante == null)
            {
                return NotFound();
            }

            return View(estudiante);
        }

        // POST: Estudiante/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var estudiante = await _context.Estudiantes.FindAsync(id);
            if (estudiante != null)
            {
                _context.Estudiantes.Remove(estudiante);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EstudianteExists(int id)
        {
            return _context.Estudiantes.Any(e => e.Id == id);
        }
    }
}

gestion des estudiantes/Gestion.web/Controllers/HomeController.cs
using Gestion.web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Gestion.web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

gestion des estudiantes/Gestion.web/Views/Estudiante/Create.cshtml
@model Gestion.domain.Entities.Estudiante

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Estudiante</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Matricula" class="control-label"></label>
                <input asp-for="Matricula" class="form-control" />
                <span asp-validation-for="Matricula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombrePadre" class="control-label"></label>
                <input asp-for="NombrePadre" class="form-control" />
                <span asp-validation-for="NombrePadre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TelefonoPadre" class="control-label"></label>
                <input asp-for="TelefonoPadre" class="form-control" />
                <span asp-validation-for="TelefonoPadre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreMadre" class="control-label"></label>
                <input asp-for="NombreMadre" class="form-control" />
                <span asp-validation-for="NombreMadre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TelefonoMadre" class="control-label"></label>
                <input asp-for="TelefonoMadre" class="form-control" />
                <span asp-validation-for="TelefonoMadre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Domicilio" class="control-label"></label>
                <input asp-for="Domicilio" class="form-control" />
                <span asp-validation-for="Domicilio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Curso" class="control-label"></label>
                <input asp-for="Curso" class="form-control" />
                <span asp-validation-for="Curso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Necesidades" class="control-label"></label>
                <input asp-for="Necesidades" class="form-control" />
                <span asp-validation-for="Necesidades" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Intervenciones" class="control-label"></label>
                <input asp-for="Intervenciones" class="form-control" />
                <span asp-validation-for="Intervenciones" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Resultados" class="control-label"></label>
                <input asp-for="Resultados" class="form-control" />
                <span asp-validation-for="Resultados" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

gestion des estudiantes/Gestion.web/Views/Estudiante/Delete.cshtml
@model Gestion.domain.Entities.Estudiante

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Estudiante</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sexo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Matricula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombrePadre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombrePadre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TelefonoPadre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TelefonoPadre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreMadre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreMadre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TelefonoMadre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TelefonoMadre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Domicilio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Domicilio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Curso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Curso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Necesidades)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Necesidades)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Intervenciones)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Intervenciones)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resultados)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Resultados)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

gestion des estudiantes/Gestion.web/Views/Estudiante/Details.cshtml
@model Gestion.domain.Entities.Estudiante

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Estudiante</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sexo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Matricula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombrePadre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombrePadre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TelefonoPadre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TelefonoPadre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreMadre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreMadre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TelefonoMadre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TelefonoMadre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Domicilio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Domicilio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Curso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Curso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Necesidades)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Necesidades)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Intervenciones)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Intervenciones)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resultados)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Resultados)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

gestion des estudiantes/Gestion.web/Views/Estudiante/Edit.cshtml
@model Gestion.domain.Entities.Estudiante

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Estudiante</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Matricula" class="control-label"></label>
                <input asp-for="Matricula" class="form-control" />
                <span asp-validation-for="Matricula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombrePadre" class="control-label"></label>
                <input asp-for="NombrePadre" class="form-control" />
                <span asp-validation-for="NombrePadre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TelefonoPadre" class="control-label"></label>
                <input asp-for="TelefonoPadre" class="form-control" />
                <span asp-validation-for="TelefonoPadre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreMadre" class="control-label"></label>
                <input asp-for="NombreMadre" class="form-control" />
                <span asp-validation-for="NombreMadre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TelefonoMadre" class="control-label"></label>
                <input asp-for="TelefonoMadre" class="form-control" />
                <span asp-validation-for="TelefonoMadre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Domicilio" class="control-label"></label>
                <input asp-for="Domicilio" class="form-control" />
                <span asp-validation-for="Domicilio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Curso" class="control-label"></label>
                <input asp-for="Curso" class="form-control" />
                <span asp-validation-for="Curso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Necesidades" class="control-label"></label>
                <input asp-for="Necesidades" class="form-control" />
                <span asp-validation-for="Necesidades" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Intervenciones" class="control-label"></label>
                <input asp-for="Intervenciones" class="form-control" />
                <span asp-validation-for="Intervenciones" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Resultados" class="control-label"></label>
                <input asp-for="Resultados" class="form-control" />
                <span asp-validation-for="Resultados" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

gestion des estudiantes/Gestion.web/Views/Estudiante/Index.cshtml
@model IEnumerable<Gestion.domain.Entities.Estudiante>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sexo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Edad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Matricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombrePadre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TelefonoPadre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreMadre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TelefonoMadre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Domicilio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Curso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Necesidades)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Intervenciones)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Resultados)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sexo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Edad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Matricula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombrePadre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TelefonoPadre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreMadre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TelefonoMadre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Domicilio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Curso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Necesidades)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Intervenciones)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Resultados)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

gestion des estudiantes/Gestion.web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

gestion des estudiantes/Gestion.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestion.web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Gestion.web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gestion.web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estudiante" asp-action="Index">Estudiantes</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Gestion.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>